name: ceta_radio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.3
  cupertino_icons: ^1.0.2
  youtube_player_iframe: ^2.3.0
  audioplayers: ^0.20.1
  google_nav_bar: ^5.0.6
  youtube_player_flutter: ^8.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2002.png"

  




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo200.jpg
    - assets/images/studio equipe.jpg
    - assets/images/Cetaradio-LeTop-NewSite.png
    - assets/images/coverShow.png
    - assets/images/CETALENTdChezNous.png
    - assets/images/CETAToiDeParler.png
    - assets/images/LeTop.png
    - assets/images/NAS.png
    - assets/images/touzazimut.jpg
    - assets/images/ADLM.png
    - assets/images/Harnes.jpg
    - assets/images/nezrouge.jpg
    - assets/images/concourschant.png
    - assets/images/SalonLBE.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700
    - family: BreeSerif-Regular
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf
          weight: 700
    - family: AlfaSlabOne-Regular
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf
          weight: 700
    - family: OleoScriptSwashCaps-Regular
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps-Regular.ttf
          weight: 700
    - family: Staatliches-Regular
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
          weight: 700
    - family: LondrinaOutline-Regular
      fonts: 
        - asset: assets/fonts/LondrinaOutline-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
